### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ahv** [mortsi/relic-map#1]
Koodi ladattu 8.1.2017 15:17

Laadukkaan näköistä koodia. Oma henkilökohtainen koodaustaitotaso heikompi niin ei suoralta kädeltä pysty näkemään mitään päivänselvää mainittavaa. Tässä kuitenkin jotain, toivonmukaan hyödyllistä:

- ConnectionTest luokan voisi nimetä uusiksi (ConnectionTry?), koska Test loppuiset luokan nimet ovat normaalisti JUnit testiluokkia.

- FileHandlerissa voisi varmuudeksi validoida parametrejä ja virhetilat voisi käsitellä käyttäjäystävällisemmin. En tiedä onko ajankäytöllisesti mielekästä lähteä rakentamaan mitään event systeemiä graafista käyttöliittymää varten, mutta arvosteluperusteissa virhetilanteiden käsittely ja koodin vikasietoisuudelle annetaan painoarvoa.

- WaypointClickListenerin mouseClicked-metodin for-each pyöräytys saattaa käydä raskaaksi jos ja kun ohjelmassa käytetään mahdollista vaihtoehtoista suurempaa (hypoteettista) tietolähdettä. Mutta ennenaikainen optimointi on soosoo joten ei siitä sen enempää.

- VariablePanKeyListenerin oletus offsetti tulee ehkä vähän tarpeettomasti kovakoodattuna (koska GUI-luokassa ainoa instanssi) konstruktorin kautta. Keybindit (ja oletusoffsetin) voisi ennenpitkää yrittää mallailla johonkin muokattavaan (ja tallennettavaan) muotoon - jos vaikka asetusvalikko tulee olemaan juttu jossain myöhemmässä versiossa.

- Guissa myös setMapDefaultLocationissa kovakoodattuna arvot.

- RelicStorage näyttää vähän tyhjältä wrapperilta, varmaankin ihan fiksua laajennattavuuden kannalta toisaalta.

toivottavasti oli jotain käyttökelpoista tässä katselmuksessa :)

**Comment by mortsi** [comment]
Moi

Tässä oli paljon hyviä pointteja, kiitos!

Ajattelin tosiaan lisätä jonkinlaista asetusvalikkoa jos ehdin vielä. Offset-arvo ja pari muuta kohtaa siis liittyy siihen.
